# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='images')),
                ('origin', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('crafting', models.TextField()),
                ('trajectory', models.TextField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bidding_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bidding_time', models.IntegerField(default=0)),
            ],
        ),
    ]
