# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 17:11
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='images')),
                ('origin', models.CharField(default='', max_length=200)),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(-2000), django.core.validators.MaxValueValidator(2020)])),
                ('description', models.TextField()),
                ('crafting', models.TextField()),
                ('trajectory', models.TextField()),
                ('by_user', models.IntegerField(default=1)),
                ('expert_value', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('minimun_bidding_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('current_bidding_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('buy_now_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20000000.00'))])),
                ('price_to_pay', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))])),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('on_bidding', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
