# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='on_bidding',
            field=models.BooleanField(default=True),
        ),
    ]
