# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20190929_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='bidding_price',
            new_name='buy_now_price',
        ),
        migrations.RenameField(
            model_name='artifact',
            old_name='buying_price',
            new_name='current_bidding_price',
        ),
        migrations.RenameField(
            model_name='artifact',
            old_name='initial_price',
            new_name='expert_value',
        ),
    ]
