# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 13:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20191124_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='buy_now_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20000000.00'))]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='current_bidding_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='expert_value',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(-2000), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
