# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_auto_20191021_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='age',
            new_name='year',
        ),
    ]
