# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_artifact_minimun_bidding_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='bidding_time',
            field=models.DateTimeField(null=True),
        ),
    ]
