# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_auto_20191021_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='price_to_pay',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
