# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_artifact_price_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='by_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='bidding_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
