# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_auto_20191024_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='end_bidding_date',
        ),
        migrations.AddField(
            model_name='artifact',
            name='bidding_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
